### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by redhat12345** [albioTQ/CNN_Visualization#2]
Hi,

I am getting the following error. Can you please help me to sort out the error?  Thanks in advanced.

Loading images from provided directories... 
Performing a forward pass on all the images.... 
Traceback (most recent call last):
  File "tsneCNN.py", line 142, in <module>
    main(sys.argv[1:])
  File "tsneCNN.py", line 111, in main
    predictions = [idx_to_synset[x] for x in predictions]
KeyError: 673

**Comment by redhat12345** [comment]
Problem Solved. Thank you.
