### ISSUE TITLE
Error tsneCNN.py

### ISSUE THREAD

**Issue by redhat12345** [albioTQ/CNN_Visualization#3]
Hi, 

I am getting the following error on tsneCNN.py while creating a movie. Otherwise, it works well. Please help to sort out this issue. Thanks in advance.

Iteration 800 : error 0.402788234608Traceback (most recent call last):
  File "tsneCNN.py", line 149, in <module>
    main(sys.argv[1:])
  File "tsneCNN.py", line 143, in main
    tsne.showMovie(positions, mappedLabels)
  File "/home/redhat/Backpropagation/caffe/python/caffe/CNN_Visualization-master/exp/tsne.py", line 262, in showMovie
    animation.save('movie.mp4')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/animation.py", line 838, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/animation.py", line 202, in saving
    self.finish()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/animation.py", line 402, in finish
    + ' Try running with --verbose-debug')
RuntimeError: Error creating movie, return code: 1 Try running with --verbose-debug

**Comment by redhat12345** [comment]
Another question regarding tSNE. When I run same program in caffe i got top 1 around 65%, but here I got only 2.3%. What is the reason, can anyone explain, please ?
